# Generated by Django 5.0.7 on 2024-09-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_account_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], default='buyer', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_img',
            field=models.FileField(default=None, upload_to='profile'),
        ),
    ]
