# Generated by Django 5.0.7 on 2024-09-07 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_dog_display_img_alter_dog_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
