# Generated by Django 5.0.7 on 2024-09-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='display_img',
            field=models.ImageField(blank=True, null=True, upload_to='dog_display_img'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=10),
        ),
    ]
