# Generated by Django 5.0.7 on 2024-09-26 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_status'),
        ('shop', '0006_dog_seller'),
    ]

    operations = [
    ]
