# Generated by Django 5.0.7 on 2024-09-26 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_dog_display_img_alter_order_status'),
        ('shop', '0007_merge_0005_alter_order_status_0006_dog_seller'),
    ]

    operations = [
    ]
